// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddFiles(arg1) {
  return window['go']['main']['App']['AddFiles'](arg1);
}

export function CancelQueue() {
  return window['go']['main']['App']['CancelQueue']();
}

export function ClearQueue() {
  return window['go']['main']['App']['ClearQueue']();
}

export function DownloadModel(arg1) {
  return window['go']['main']['App']['DownloadModel'](arg1);
}

export function DownloadWhisperCLI() {
  return window['go']['main']['App']['DownloadWhisperCLI']();
}

export function GetAvailableModels() {
  return window['go']['main']['App']['GetAvailableModels']();
}

export function GetHardwareSpecs() {
  return window['go']['main']['App']['GetHardwareSpecs']();
}

export function GetQueue() {
  return window['go']['main']['App']['GetQueue']();
}

export function GetRecommendedModel() {
  return window['go']['main']['App']['GetRecommendedModel']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetWhisperPath() {
  return window['go']['main']['App']['GetWhisperPath']();
}

export function IsModelDownloaded(arg1) {
  return window['go']['main']['App']['IsModelDownloaded'](arg1);
}

export function IsProcessing() {
  return window['go']['main']['App']['IsProcessing']();
}

export function IsWhisperInstalled() {
  return window['go']['main']['App']['IsWhisperInstalled']();
}

export function PauseQueue() {
  return window['go']['main']['App']['PauseQueue']();
}

export function RemoveFile(arg1) {
  return window['go']['main']['App']['RemoveFile'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SelectFiles() {
  return window['go']['main']['App']['SelectFiles']();
}

export function SelectOutputDirectory() {
  return window['go']['main']['App']['SelectOutputDirectory']();
}

export function SetWindowFrame(arg1) {
  return window['go']['main']['App']['SetWindowFrame'](arg1);
}

export function StartQueue(arg1, arg2) {
  return window['go']['main']['App']['StartQueue'](arg1, arg2);
}

export function WindowClose() {
  return window['go']['main']['App']['WindowClose']();
}

export function WindowMinimize() {
  return window['go']['main']['App']['WindowMinimize']();
}

export function WindowToggleMaximize() {
  return window['go']['main']['App']['WindowToggleMaximize']();
}
