// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {queue} from '../models';
import {models} from '../models';
import {hardware} from '../models';
import {config} from '../models';

export function AddFiles(arg1:Array<string>):Promise<Array<queue.TaskInfo>>;

export function CancelQueue():Promise<void>;

export function ClearQueue():Promise<void>;

export function DownloadModel(arg1:string):Promise<void>;

export function DownloadWhisperCLI():Promise<void>;

export function GetAvailableModels():Promise<Array<models.ModelInfo>>;

export function GetHardwareSpecs():Promise<hardware.Specs>;

export function GetQueue():Promise<Array<queue.TaskInfo>>;

export function GetRecommendedModel():Promise<models.ModelInfo>;

export function GetSettings():Promise<config.Settings>;

export function GetWhisperPath():Promise<string>;

export function IsModelDownloaded(arg1:string):Promise<boolean>;

export function IsProcessing():Promise<boolean>;

export function IsWhisperInstalled():Promise<boolean>;

export function PauseQueue():Promise<void>;

export function RemoveFile(arg1:string):Promise<void>;

export function SaveSettings(arg1:config.Settings):Promise<void>;

export function SelectFiles():Promise<Array<string>>;

export function SelectOutputDirectory():Promise<string>;

export function SetWindowFrame(arg1:string):Promise<void>;

export function StartQueue(arg1:string,arg2:string):Promise<void>;

export function WindowClose():Promise<void>;

export function WindowMinimize():Promise<void>;

export function WindowToggleMaximize():Promise<void>;
